name: Runs cronjobs

on:
  schedule:
    - cron: '* * * * *'

jobs:
  sayHi:
    runs-on: self-hosted
    steps:
      - run: echo "âœ¨ Running job"
      - name: Checkout latest code
        uses: actions/checkout@v2
      - run: echo "ðŸ–¥ Current status ${{ job.status }}"
